namespace CDO.Core.DTOs.Admin;

public record class AdminClientDetail(
    // Non-optional fields
    int Id,
    string FirstName,
    string LastName,
    bool Active,
    bool Ttw,
    string City,
    string State,
    string Disability,

    // Nullable fields
    DateTime? CreatedAt,
    DateTime? UpdatedAt,
    DateTime? StartDate,
    int? CounselorID,
    string? Ssn,
    string? CaseID,
    string? Address1,
    string? Address2,
    string? Zip,
    DateTime? Dob,
    string? DriversLicense,
    string? Phone1,
    string? Phone1Identity,
    string? Phone2,
    string? Phone2Identity,
    string? Phone3,
    string? Phone3Identity,
    string? Email,
    string? EmailIdentity,
    string? Email2,
    string? Email2Identity,
    string? Conditions,
    string? EmploymentGoal,
    string? Status,
    string? Benefits,
    string? CriminalCharge,
    string? Education,
    string? Transportation,
    bool? ResumeRequired,
    bool? ResumeCompleted,
    bool? VideoInterviewRequired,
    bool? VideoInterviewCompleted,
    bool? ReleasesCompleted,
    bool? OrientationCompleted,
    bool? DataSheetCompleted,
    bool? ElevatorSpeechCompleted,
    string? Race,
    string? FluentLanguages,
    string? Premiums
);