namespace CDO.Core.DTOs.Clients;

public record class NewClient(
    // Required creation fields
    string FirstName,
    string LastName,
    string City,
    string State,
    string Disability,
    bool TTW,


    // Optional fields
    int? Ssn,
    string? CaseID,
    string? Address1,
    string? Address2,
    string? Zip,
    DateTime? Dob,
    DateTime? StartDate,
    string? DriversLicense,
    string? Phone1,
    string? Phone1Identity,
    string? Phone2,
    string? Phone2Identity,
    string? Phone3,
    string? Phone3Identity,
    string? Email,
    string? EmailIdentity,
    string? Email2,
    string? Email2Identity,
    int? CounselorID,
    string? ClientNotes,
    string? Conditions,
    string? DocumentFolder,
    bool? Active,
    string? EmploymentGoal,
    int? EmployerID,
    string? Status,
    string? Benefits,
    string? CriminalCharge,
    string? Education,
    string? Transportation,
    bool? ResumeRequired,
    bool? ResumeCompleted,
    bool? VideoInterviewRequired,
    bool? VideoInterviewCompleted,
    bool? ReleasesCompleted,
    bool? OrientationCompleted,
    bool? DataSheetCompleted,
    bool? ElevatorSpeechCompleted,
    string? Race,
    string? FluentLanguages,
    string? Premiums
    );