namespace CDO.Core.DTOs;

public class UpdateClientDTO {
    public string? FirstName { get; set; }
    public string? LastName { get; set; }
    public string? City { get; set; }
    public string? Disability { get; set; }
    public string? State { get; set; }
    public int? Ssn { get; set; }
    public string? CaseID { get; set; }
    public string? Address1 { get; set; }
    public string? Address2 { get; set; }
    public string? Zip { get; set; }
    public DateTime? Dob { get; set; }
    public DateTime? StartDate { get; set; }
    public string? DriversLicense { get; set; }
    public string? Phone1 { get; set; }
    public string? Phone1Identity { get; set; }
    public string? Phone2 { get; set; }
    public string? Phone2Identity { get; set; }
    public string? Phone3 { get; set; }
    public string? Phone3Identity { get; set; }
    public string? Email { get; set; }
    public string? EmailIdentity { get; set; }
    public string? Email2 { get; set; }
    public string? Email2Identity { get; set; }
    public int? CounselorID { get; set; }
    public string? ClientNotes { get; set; }
    public string? Conditions { get; set; }
    public string? DocumentFolder { get; set; }
    public bool? Active { get; set; }
    public string? EmploymentGoal { get; set; }
    public int? EmployerID { get; set; }
    public string? Status { get; set; }
    public string? Benefits { get; set; }
    public string? CriminalCharge { get; set; }
    public string? Education { get; set; }
    public string? Transportation { get; set; }
    public bool? ResumeRequired { get; set; }
    public bool? ResumeCompleted { get; set; }
    public bool? VideoInterviewRequired { get; set; }
    public bool? VideoInterviewCompleted { get; set; }
    public bool? ReleasesCompleted { get; set; }
    public bool? OrientationCompleted { get; set; }
    public bool? DataSheetCompleted { get; set; }
    public bool? ElevatorSpeechCompleted { get; set; }
    public string? Race { get; set; }
    public string? FluentLanguages { get; set; }
    public string? Premiums { get; set; }
}