namespace CDO.Core.DTOs;

public class UpdateClientDTO {
    public string? firstName { get; set; }
    public string? lastName { get; set; }
    public string? counselor { get; set; }
    public string? city { get; set; }
    public string? disability { get; set; }
    public string? state { get; set; }
    public int? ssn { get; set; }
    public string? caseID { get; set; }
    public string? address1 { get; set; }
    public string? address2 { get; set; }
    public string? zip { get; set; }
    public DateTime? dob { get; set; }
    public DateTime? startDate { get; set; }
    public string? driversLicense { get; set; }
    public string? phone1 { get; set; }
    public string? phone1Identity { get; set; }
    public string? phone2 { get; set; }
    public string? phone2Identity { get; set; }
    public string? phone3 { get; set; }
    public string? phone3Identity { get; set; }
    public string? email { get; set; }
    public string? emailIdentity { get; set; }
    public string? email2 { get; set; }
    public string? email2Identity { get; set; }
    public int? counselorID { get; set; }
    public string? counselorEmail { get; set; }
    public string? counselorPhone { get; set; }
    public string? counselorFax { get; set; }
    public string? clientNotes { get; set; }
    public string? conditions { get; set; }
    public string? documentFolder { get; set; }
    public bool? active { get; set; }
    public string? employmentGoal { get; set; }
    public int? employerID { get; set; }
    public string? status { get; set; }
    public string? benefit { get; set; }
    public string? criminalCharge { get; set; }
    public string? education { get; set; }
    public string? transportation { get; set; }
    public bool? resumeRequired { get; set; }
    public bool? resumeCompleted { get; set; }
    public bool? videoInterviewRequired { get; set; }
    public bool? videoInterviewCompleted { get; set; }
    public bool? releasesCompleted { get; set; }
    public bool? orientationCompleted { get; set; }
    public bool? dataSheetCompleted { get; set; }
    public bool? elevatorSpeechCompleted { get; set; }
    public string? race { get; set; }
    public string? fluentLanguages { get; set; }
    public string? premium { get; set; }
}